<?php
namespace App\Http\Controllers;
use App\Models\UploadLog;
use App\Services\ClaudeExtractor;
use App\Services\DocumentExtractor;
use App\Services\IrisService;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Validation\Rules\File;
class AdminController extends Controller {
 public function dashboard(Request $r){$logs=UploadLog::orderByDesc('uploaded_at')->limit(10)->get();return view('admin.dashboard',['msg'=>$r->query('msg'),'logs'=>$logs]);}
 public function smartUpload(Request $r){$checks=ClaudeExtractor::checks();return view('admin.smart_upload',['msg'=>$r->query('msg'),'checks'=>$checks,'allOk'=>ClaudeExtractor::requirementsOk($checks)]);}
 public function uploadCsv(Request $r){$r->validate(['upload_type'=>'required|in:rankings,colleges,programs','csv_file'=>'required|file']);$file=$r->file('csv_file');$rowsInserted=0;$type=$r->upload_type;$rows=IrisService::csvRows($file->getRealPath());foreach($rows as $row){if($type==='rankings'){[$s,$y,$g,$p,$n]=array_pad(array_values($row),5,null);if(IrisService::insertRanking($s,$y,null,$g,$p,$n))$rowsInserted++;}elseif($type==='colleges'){[$name,$code,$percent,$year]=array_pad(array_values($row),4,null);if(IrisService::insertCollege($name,$code,$percent,$year))$rowsInserted++;}else{[$name,$code,$rank,$score,$movement,$year]=array_pad(array_values($row),6,null);if(IrisService::insertProgram($name,$code,$rank,$score,$movement,$year))$rowsInserted++;}}UploadLog::create(['uploaded_by'=>$r->user()->id,'filename'=>basename($file->getClientOriginalName()),'file_type'=>'csv','upload_type'=>$type,'rows_inserted'=>$rowsInserted]);return redirect()->route('admin.dashboard')->with('msg','Uploaded '.basename($file->getClientOriginalName()).' — '.$rowsInserted.' rows inserted.');}
 public function smartUploadProcess(Request $r){$r->validate(['upload_file'=>'required|file|max:15360']);$file=$r->file('upload_file');$name=basename($file->getClientOriginalName());$ext=strtolower($file->getClientOriginalExtension());$allowed=['csv','xlsx','xls','docx','pdf','jpg','jpeg','png'];if(!in_array($ext,$allowed))return redirect()->route('admin.smart-upload')->with('msg','Unsupported file type: .'.$ext);try{$result=null;if($ext==='csv'){$result=IrisService::smartMapCsv($file->getRealPath());if($result===null){$checks=ClaudeExtractor::checks();if(!ClaudeExtractor::requirementsOk($checks))return redirect()->route('admin.smart-upload')->with('msg',"This CSV's columns don't match rankings/colleges/programs, so it needs AI help to read — but the AI isn't fully configured yet. See the Setup Status panel below for what's missing.");$result=ClaudeExtractor::extract([ClaudeExtractor::textBlock(IrisService::csvText($file->getRealPath()))]);}}else{$checks=ClaudeExtractor::checks();if(!ClaudeExtractor::requirementsOk($checks))return redirect()->route('admin.smart-upload')->with('msg',"AI extraction isn't fully configured on this server yet. See the Setup Status panel below for what's missing.");$blocks=[];if(in_array($ext,['xlsx','xls']))$blocks[] = ClaudeExtractor::textBlock(DocumentExtractor::spreadsheet($file->getRealPath()));elseif($ext==='docx')$blocks[]=ClaudeExtractor::textBlock(DocumentExtractor::docx($file->getRealPath()));elseif($ext==='pdf')$blocks[]=ClaudeExtractor::pdfBlock($file->getRealPath());else $blocks[]=ClaudeExtractor::imageBlock($file->getRealPath(),$ext==='png'?'image/png':'image/jpeg');$result=ClaudeExtractor::extract($blocks);} $r->session()->put(['pending_extraction'=>$result,'pending_extraction_filename'=>$name,'pending_extraction_file_type'=>$ext]);return redirect()->route('admin.review-extraction');}catch(\Throwable $e){report($e);return redirect()->route('admin.smart-upload')->with('msg',$e->getMessage());}}
 public function reviewExtraction(Request $r){if(!$r->session()->has('pending_extraction'))return redirect()->route('admin.smart-upload');$data=$r->session()->get('pending_extraction');return view('admin.review_extraction',['data'=>$data,'filename'=>$r->session()->get('pending_extraction_filename','uploaded file'),'fileType'=>$r->session()->get('pending_extraction_file_type',''),'rankings'=>$data['rankings']??[],'breakdowns'=>$data['ranking_breakdowns']??[],'colleges'=>$data['colleges']??[],'programs'=>$data['programs']??[],'accreditations'=>$data['accreditations']??[],'totalRows'=>count($data['rankings']??[])+count($data['ranking_breakdowns']??[])+count($data['colleges']??[])+count($data['programs']??[])+count($data['accreditations']??[])]);}
 public function smartUploadConfirm(Request $r){
  $inserted=0; $skipped=0; $categories=[];
  foreach($r->input('rankings',[]) as $v){ if(!isset($v['include'])) continue; if(IrisService::insertRanking($v['ranking_body_short_name'],$v['year'],$v['category']??null,$v['global_rank'],$v['ph_rank'],$v['note'])){$inserted++;$categories['rankings']=true;}else{$skipped++;} }
  foreach($r->input('breakdowns',[]) as $v){ if(!isset($v['include'])) continue; if(IrisService::insertBreakdown($v['ranking_body_short_name'],$v['year'],$v['group_label']??null,$v['item_label'],$v['rank_display'],$v['note']??'')){$inserted++;$categories['ranking_breakdowns']=true;}else{$skipped++;} }
  foreach($r->input('colleges',[]) as $v){ if(!isset($v['include'])) continue; if(IrisService::insertCollege($v['name'],$v['short_code'],$v['contribution_percent'],$v['year'])){$inserted++;$categories['colleges']=true;}else{$skipped++;} }
  foreach($r->input('programs',[]) as $v){ if(!isset($v['include'])) continue; if(IrisService::insertProgram($v['name'],$v['college_short_code'],$v['national_rank'],$v['score'],$v['movement'],$v['year'])){$inserted++;$categories['programs']=true;}else{$skipped++;} }
  foreach($r->input('accreditations',[]) as $v){ if(!isset($v['include'])) continue; if(IrisService::insertAccreditation($v['program_name'],$v['accrediting_body']??'AUN-QA',$v['year'],$v['assessment_date']??null,$v['criterion'],$v['score'])){$inserted++;$categories['accreditations']=true;}else{$skipped++;} }
  $filename=trim((string)$r->session()->get('pending_extraction_filename','unknown')); $fileType=trim((string)$r->input('file_type',$r->session()->get('pending_extraction_file_type',''))); $uploadType=count($categories)===1?array_key_first($categories):(count($categories)>1?'mixed':'none');
  UploadLog::create(['uploaded_by'=>$r->user()->id,'filename'=>$filename,'file_type'=>$fileType,'upload_type'=>$uploadType,'rows_inserted'=>$inserted]);
  $r->session()->forget(['pending_extraction','pending_extraction_filename','pending_extraction_file_type']);
  $msg='Saved '.$inserted.' row(s).'; if($skipped>0)$msg.=' '.$skipped.' row(s) skipped (e.g. unknown ranking body, or a college/program code that doesn\'t exist yet — add that college first).'; return redirect()->route('admin.dashboard')->with('msg',$msg);
 }

}
