<?php
require_once __DIR__.'/functions.php';
const IRIS_AI_PROMPT=<<<'PROMPT'
You are extracting university ranking, accreditation, and organizational data from a document for a dashboard system.
Return ONLY valid JSON in exactly this shape: {"rankings":[],"ranking_breakdowns":[],"colleges":[],"programs":[],"accreditations":[]}.
Ranking row fields: ranking_body_short_name, year, category, global_rank, ph_rank, note.
Breakdown fields: ranking_body_short_name, year, group_label, item_label, rank_display, note.
College fields: name, short_code, contribution_percent, year.
Program fields: name, college_short_code, national_rank, score, movement, year.
Accreditation fields: program_name, accrediting_body, year, assessment_date, criterion, score.
Use published rank text exactly; do not invent numbers. Empty categories must be empty arrays.
PROMPT;
function ai_requirements():array{$key=(bool)getenv('CLAUDE_API_KEY');return ['api_key'=>['ok'=>$key,'label'=>$key?'CLAUDE_API_KEY is set.':'CLAUDE_API_KEY is not set.'],'curl'=>['ok'=>function_exists('curl_init'),'label'=>function_exists('curl_init')?'PHP cURL extension enabled.':'PHP cURL extension is missing.'],'zip'=>['ok'=>class_exists('ZipArchive'),'label'=>class_exists('ZipArchive')?'ZipArchive available.':'PHP zip extension is missing.'],'fileinfo'=>['ok'=>function_exists('finfo_open'),'label'=>function_exists('finfo_open')?'fileinfo extension enabled.':'fileinfo extension is missing.']];}
function ai_extract(array $blocks):array{$key=getenv('CLAUDE_API_KEY');if(!$key)throw new RuntimeException('AI extraction is not configured: set CLAUDE_API_KEY in the Apache environment.');$payload=['model'=>getenv('CLAUDE_MODEL')?:'claude-sonnet-4-6','max_tokens'=>3000,'messages'=>[['role'=>'user','content'=>array_merge([['type'=>'text','text'=>IRIS_AI_PROMPT]],$blocks)]]];$ch=curl_init('https://api.anthropic.com/v1/messages');curl_setopt_array($ch,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_POST=>true,CURLOPT_HTTPHEADER=>['x-api-key: '.$key,'anthropic-version: 2023-06-01','Content-Type: application/json'],CURLOPT_POSTFIELDS=>json_encode($payload),CURLOPT_TIMEOUT=>90]);$raw=curl_exec($ch);$code=curl_getinfo($ch,CURLINFO_HTTP_CODE);$err=curl_error($ch);curl_close($ch);if($raw===false)throw new RuntimeException('AI request failed: '.$err);$resp=json_decode($raw,true);if($code>=400)throw new RuntimeException('The Anthropic API rejected the request (HTTP '.$code.'): '.($resp['error']['message']??$raw));$text=$resp['content'][0]['text']??'';$a=strpos($text,'{');$b=strrpos($text,'}');if($a===false||$b===false)throw new RuntimeException('Could not find structured data in the AI response.');$parsed=json_decode(substr($text,$a,$b-$a+1),true);if(!is_array($parsed))throw new RuntimeException('Could not parse the AI response as JSON.');return ['rankings'=>$parsed['rankings']??[],'ranking_breakdowns'=>$parsed['ranking_breakdowns']??[],'colleges'=>$parsed['colleges']??[],'programs'=>$parsed['programs']??[],'accreditations'=>$parsed['accreditations']??[]];}
